name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - shell: bash
      run: pnpm install

    - name: Copy .env.example files
      shell: bash
      run:
        find ./examples -type f -name ".env.example" -exec sh -c 'cp "$1"
        "${1%.example}"' _ {} \;
