name: Examples E2E

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  e2e-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        dir:
          [
            minimal-appdir,
            minimal-pagedir
          ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/gh-actions/setup

      - name: Build UT packages
        run: pnpm run build

      - name: Run build
        run: pnpm turbo --filter ./examples/${{ matrix.dir }} build
