name: Publish Test Releases
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/gh-actions/setup

      - name: Build
        run: pnpm turbo build --filter "./packages/*"

      #TODO: would be nice to filter on acutually changed packages
      - run: pnpx pkg-pr-new publish ./packages/*