name: Lint the PR Title & Add Labels

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  check-title:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: 'Pull Request Labeler'

  add-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
