name: Close Inactive Issues
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 10
          days-before-issue-close: 5
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been automatically marked as stale because it has not had any activity for 10 days. It will be closed in 5 days if no further activity occurs."
          close-issue-message: "This issue has been closed because it has not had any activity for 5 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exempt-issue-labels: "planned,PRs Accepted,bug: low priority,bug: medium priority,bug: high priority,workaround available,🙋‍♂️ help wanted,in progress"
